version: "3"

services:
  app:
    container_name: chamilo
    build: .
    image: chamilo/chamilo
    volumes:
      - "./config/php.ini:/usr/local/etc/php/conf.d/uploads.ini"
      - "./chamilo:/var/www/html"
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - data_db:/var/lib/mysql
      - "./db:/tmp/db"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

volumes:
  data_db: {}